# Install script for directory: /var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/cuneiform_src/Kern

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "debug")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/ccom/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/cstr/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rstr/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rpstr/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/cline/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/fon/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/leo/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/evn32/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/cpage/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/cimage/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/cfio/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/puma/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rline/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rcutp/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/dif/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/msk/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rling/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/ctb/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rsadd/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/std/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/pass2/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rbal/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/mmx/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/r35/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/cpu/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rdib/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/loc/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/ced/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/exc/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rimage/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rverline/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rout/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rblock/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rselstr/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rfrmt/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rshelllines/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/lns32/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rreccom/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/smetric/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rneg/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rpic/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rstuff/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rmarker/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/rcorrkegl/cmake_install.cmake")
  INCLUDE("/var/www/imater/data/www/4tree.ru/cuneiform-linux-1.1.0/builddir/cuneiform_src/Kern/cfcompat/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

